### PR TITLE
updated supported python versions

### PR DESCRIPTION
**Pull request by petrem**

### CODE REVIEW

**Comment by Stranger6667** [comment]
Nice! 

Thank you for contribution @petrem :)

I think that removing Python 3.7 is too early (it has ~16 months till EOL). Other than that, could you, please add a note to the changelog?

**Comment by petrem** [comment]
apologies, I opened this by mistake!

**Comment by Stranger6667** [comment]
No worries! :)

**Comment by petrem** [comment]
Thank you for responding, I'm working on this. Glad you find it useful, I'll try to make a proper one soon.

**Comment by Stranger6667** [comment]
Sure thing! Let me know if there is anything I can help with :)

**Pull request closed without merging**
